version: '3'
services:
  web:
    build: app/
    links:
      - cache
      - db
  cache:
    image: memcached
  db:
    image: mysql:5
    volumes:
      - ./mysql-data.sql:/docker-entrypoint-initdb.d/mysql-data.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=mysecretpw"
      - "MYSQL_DATABASE=sportsdb"
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx-load-balance.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000"
    links:
      - web
